auth_user/urls.py
from django.urls import path
from .views import login_user,signup,home,logout_user

urlpatterns = [
    path('', home,name='home'),
    path('login', login_user,name='login'),
    path('signup', signup,name='signup'),
    path('logout', logout_user,name='logout'),
]
app_name = 'auth_user'

ottclone/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('auth_user.urls',namespace='auth')),
    path('show/',include('shows.urls',namespace='show')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shows/urls.py
from django.urls import path
from .views import create_show, show_show, allitems,show_item,history,allshow

urlpatterns = [
    path('',show_show,name='show'),
    path('add',create_show,name='create'),
    path('allitems/<str:catagory_name>',allitems,name='allitems'),
    path('showitem/<int:pk>',show_item,name='show_item'),
    path('history',history,name='history'),
    path('allshow',allshow,name='allshow'),
]

app_name = 'shows'

shows/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import render
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from .validators import input_validation, image_validation, vedio_validation

class catagories(models.Model):
    catagorie_name = models.CharField('catagorie',max_length=100)

    class Meta:
        db_table = 'catagoires'
        verbose_name_plural = 'catagoires'

    def __str__(self):
        return self.catagorie_name.title()
    
    def get_absolute_url(self):
        return reverse('show:allitems',args=[str(self.catagorie_name)])

class show(models.Model):
    show_authors = models.ForeignKey(User, on_delete = models.CASCADE, null=False,related_name='show_related')
    show_name = models.CharField('show name', max_length=100, db_column='show_name',validators=[input_validation])
    show_upload_date = models.DateField(auto_now_add=True,verbose_name='upload date')
    show_title = models.CharField('show title', max_length=100, db_column='show_title',validators=[input_validation])
    show_description = models.CharField('show description', max_length=100, db_column='show_description',validators=[input_validation])
    show_caption = models.ImageField(verbose_name='show caption',upload_to='shows',validators=[image_validation])
    show_catagory = models.ForeignKey(catagories, on_delete=models.CASCADE, verbose_name='catagory', related_name='catagory_related', related_query_name='query_catagory')
    show_vedio = models.FileField(upload_to='vedio',verbose_name='show vedio',validators=[vedio_validation])

    class Meta:
        db_table = 'show_table'
        get_latest_by = ['-show_upload_date']
        verbose_name_plural = 'show'
    
    def __str__(self):
        return self.show_name

    def get_absolute_url(self):
        return reverse('show:show_item',args=[int(self.id)])

class watch_history(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, related_name='history_related', related_query_name='history_query')
    waths = models.ManyToManyField(show, related_name='show_many')


@receiver(post_save, sender = User)
def watch_created(sender, instance, created, **kwargs):
    if created:
        watch_history.objects.create(user = instance)

shows/forms.py
from django.forms import ModelForm
from django import forms
from .models import show

class showform(ModelForm):
    class Meta:
        model = show
        fields = ['show_name', 'show_title', 'show_description', 'show_caption','show_catagory', 'show_vedio']
        widgets = {
            'show_name':forms.TextInput(attrs={'class':'form-control  bg-dark text-white', 'autofocus':True}),
            'show_title':forms.TextInput(attrs={'class':'form-control  bg-dark text-white'}),
            'show_description':forms.TextInput(attrs={'class':'form-control  bg-dark text-white'}),
            'show_caption':forms.FileInput(attrs={'class':'form-control  bg-dark text-white ','aria-label':"file example"}),
            'show_catagory':forms.Select(attrs={'class':'form-control  bg-dark text-white'}),
            'show_vedio':forms.FileInput(attrs={'class':'form-control  bg-dark text-white'}),
        }

shows/views.py
from django import contrib
from django.contrib import messages
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from .forms import showform
from django.contrib.auth.models import User
from .models import show,watch_history
from django.contrib.auth.decorators import login_required

def create_show(request):

    if request.user.is_authenticated:
        show_form_instance = showform
        form = show_form_instance(request.POST or None )

        if request.method == 'POST':
            form = showform(request.POST, request.FILES)
            if form.is_valid():
                show = form.cleaned_data.get('show_name')
                intial = form.save(commit=False)
                intial.show_authors = request.user
                intial.save()
                messages.success(request,f'show saved for {show}.')
                return redirect('show:create')
        
        context = {'htmlform':form}
        return render(request,'addshow.html',context)
    else:
        return redirect('auth:home')    

def show_show(request):

    # if request.user.is_authenticated:
        shows = show.objects.all().only('show_name','show_title','show_vedio')
        
        context = {'show':shows}
        return render(request,'show.html',context)
    # else:
    #     return redirect('auth:home') 
 
def allitems(request,catagory_name):
    all_show = show.objects.filter(show_catagory__catagorie_name__icontains = catagory_name )
    context = {'all_items':all_show}
    return render(request,'allofcatagory.html', context)


def show_item(request,pk):
    item = show.objects.get(id = pk)
    user_name = request.user
    if request.user.is_authenticated:
        watch_history_person = watch_history.objects.get(user =user_name)
        watch_history_person.waths.add(pk)
    context = {'item':item}
    return render(request,'vedio.html',context)
    
@login_required(login_url='auth:login')
def history(request):
    user = request.user
    watchs = user.history_related
    vedio = watchs.waths.all
    context = {'watch':vedio}
    return render(request,'history.html', context)

def allshow(request):
    user = User.objects.get(id = request.user.id)
    items = user.show_related.all()
    context = {'items':items}
    return render(request,'entershow.html',context)

templates/addshow.html
{% extends 'navbar.html' %}
{% block title %}
    Add | show
{% endblock %}

{% block form %}
<div class="container mt-3 ">
    {{htmlform.non_field_errors}}
    <form action="{% url 'show:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row justify-content-center">
            <div class="col col-md-4">
                <h4>Add show</h4>
            </div>
            <div class="w-100"></div>
            <div class="col col-md-2">
                <label class="form-label" for="{{htmlform.show_name.id_for_label}}">{{htmlform.show_name.label}}</label>
                {{htmlform.show_name}}

                {% if htmlform.show_name.errors %}
                <script>
                    var user = '{{htmlform.show_name.id_for_label}}';
                    var user_add_class = document.getElementById(user);
                    user_add_class.classList.add('is-invalid')
                </script>
                {% for error in htmlform.show_name.errors %}
                    <div class="invalid-feedback">
                        {{error}}
                    </div>
                {% endfor %}
                {% endif %}
            </div>
            <div class="col col-md-2">
                <label class="form-label" for="{{htmlform.show_title.id_for_label}}">{{htmlform.show_title.label}}</label>
                {{htmlform.show_title}}
                {% if htmlform.show_title.errors %}
                <script>
                    var user = '{{htmlform.show_title.id_for_label}}';
                    var user_add_class = document.getElementById(user);
                    user_add_class.classList.add('is-invalid')
                </script>
                {% for error in htmlform.show_title.errors %}
                    <div class="invalid-feedback">
                        {{error}}
                    </div>
                {% endfor %}
                {% endif %}
            </div>
            <div class="w-100"></div>
            <div class="col-12 col-md-4">
                <label class="form-label" for="{{htmlform.show_description.id_for_label}}">{{htmlform.show_description.label}}</label>
                {{htmlform.show_description}}
                {% if htmlform.show_description.errors %}
                <script>
                    var user = '{{htmlform.show_description.id_for_label}}';
                    var user_add_class = document.getElementById(user);
                    user_add_class.classList.add('is-invalid')
                </script>
                {% for error in htmlform.show_description.errors %}
                    <div class="invalid-feedback">
                        {{error}}
                    </div>
                {% endfor %}
                {% endif %}
            </div>
            <div class="w-100"></div>
            <div class="col-12 col-md-4">
                <label class="form-label" for="{{htmlform.show_caption.id_for_label}}">{{htmlform.show_caption.label}}</label>
                {{htmlform.show_caption}}
                <!-- {{htmlform.show_caption.errors}} -->
                {% if htmlform.show_caption.errors %}
                        <script>
                            var user = '{{htmlform.show_caption.id_for_label}}';
                            var user_add_class = document.getElementById(user);
                            user_add_class.classList.add('is-invalid')
                        </script>
                    {% for error in htmlform.show_caption.errors %}
                    <div class="invalid-feedback">
                        {{error}}
                    </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="w-100"></div>
            <div class="col-12 col-md-4">
                <label class="form-label" for="{{htmlform.show_catagory.id_for_label}}">{{htmlform.show_catagory.label}}</label>
                {{htmlform.show_catagory}}
                {% if htmlform.show_catagory.errors %}
                    <script>
                        var elementhello = '{{htmlform.show_catagory.id_for_label}}';
                        var user_add_class = document.getElementById(elementhello);
                        user_add_class.classList.add('is-invalid')
                    </script>
                    {% for error in htmlform.show_catagory.errors %}
                        <div class="invalid-feedback">
                            {{error}}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="w-100"></div>
            <div class="col-12 col-md-4">

                <label class="form-label" for="{{htmlform.show_vedio.id_for_label}}">{{htmlform.show_vedio.label}}</label>
                {{htmlform.show_vedio}}
                   {% if htmlform.show_vedio.errors %}
                <script>
                    var elementhello = '{{htmlform.show_vedio.id_for_label}}';
                    var user_add_class = document.getElementById(elementhello);
                    user_add_class.classList.add('is-invalid')
                </script>
                {% for error in htmlform.show_vedio.errors %}
                    <div class="invalid-feedback">
                        {{error}}
                    </div>
                {% endfor %}
            {% endif %}
            </div>
            <div class="w-100"></div>
            <div class="col-12 col-md-4 ">
                <button type="submit" class="btn btn-primary w-100 mt-2">Upload</button>
            </div>
            <div class="w-100"></div>
        </div>

    </form>
</div>
{% endblock %}

templates/allofcatagory.html
{% extends 'navbar.html' %}
{% block items %}
<div class="container">
    <style>
        .style{
            width:14rem;
            height:9rem;
            border: solid;
            border-radius: 5px;
            border-color: white;
            opacity: 0.5;
        }
        .style:hover{
            opacity: 0.8;
        }
    </style>
    <div class="row">
        {% for item in all_items %}
        <div class="col ">
            <a href="{{item.get_absolute_url}}">
                <img src="{{item.show_caption.url}}" alt="hello" class="style">
            </a>
        </div>
        {% empty %}
        <p class="text-center fs-1">No show for this catagory</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
</head>
<body class=" text-white" style="background-color: #161b22;">
<div class="container-fluid">
        {% if messages %}
            {% for message in messages %}
                {% ifequal message.tags 'warning' %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endifequal %}
                {% ifequal message.tags 'error' %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endifequal %}
                {% ifequal message.tags 'success' %}
                <div class="alert alert-success" role="alert">{{message}}</div>
                {% endifequal %}
            {% endfor %}
        {% endif %}
</div>
        {% block navbar %}
        {% endblock %}

    <div class="container mt-3">
        <div class="row justify-content-center">
            <div class="col-4 text-center">
                {% block logo %}
        
                {% endblock %}
            </div>
        </div>

    </div>
    <div id="forms">
        {% block form %}
        
        {% endblock %}
    </div>

    {% block items %}
    {% endblock %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
</body>
</html>

templates/card.html
{% extends 'navbar.html' %}
{% block items %}

{% if request.user.is_authenticated %}
    <div class="container">
        <style>
            .style{
                width:14rem;
                height:9rem;
                border: solid;
                border-radius: 5px;
                border-color: white;
                opacity: 0.5;
            }
            .style:hover{
                opacity: 0.8;
            }
        </style>
        <p class="lead">Continue watching</p>
        <div class="row d-flex flex-row flex-nowrap overflow-auto">
            {% for items in history %}
            <div class="col ">
                <a href="{{items.get_absolute_url}}">
                    <img src="{{items.show_caption.url}}" alt="hello" class="style">
                </a>
            </div>
            {% endfor %}
        </div>
            <a href="{% url 'show:history'  %}" class="text-decoration-none">see more</a>
    </div>
{% endif %}

<div class="container">
    <style>
        .style{
            width:14rem;
            height:9rem;
            border: solid;
            border-radius: 5px;
            border-color: white;
            opacity: 0.5;
        }
        .style:hover{
            opacity: 0.8;
        }
    </style>
    <p class="lead">Actions</p>
    <div class="row d-flex flex-row flex-nowrap overflow-auto">
        {% for items in show_item %}
        <div class="col ">
            <a href="{{items.get_absolute_url}}">
                <img src="{{items.show_caption.url}}" alt="hello" class="style">
            </a>
        </div>
        {% endfor %}
    </div>
        <a href="{% url 'show:allitems' 'actions' %}" class="text-decoration-none">see more</a>
</div>

<div class="container">
    <style>
        .style{
            width:14rem;
            height:9rem;
            border: solid;
            border-radius: 5px;
            border-color: white;
            opacity: 0.5;
        }
        .style:hover{
            opacity: 0.8;
        }
    </style>
    <p class="lead">Movies</p>
    <div class="row d-flex flex-row flex-nowrap overflow-auto">
        {% for item in romance %}
        <div class="col ">
            <a href="{{item.get_absolute_url}}">
                <img src="{{item.show_caption.url}}" alt="hello" class="style">
            </a>
        </div>
        {% endfor %}
    </div>
        <a href="{% url 'show:allitems' 'movies' %}" class="text-decoration-none">see more</a>
</div>

<div class="container">
    <style>
        .style{
            width:14rem;
            height:9rem;
            border: solid;
            border-radius: 5px;
            border-color: white;
            opacity: 0.5;
        }
        .style:hover{
            opacity: 0.8;
        }
    </style>
    <p class="lead">Originals</p>
    <div class="row d-flex flex-row flex-nowrap overflow-auto">
        {% for item in originals %}
        <div class="col ">
            <a href="{{item.get_absolute_url}}">
                <img src="{{item.show_caption.url}}" alt="hello" class="style">
            </a>
        </div>
        {% endfor %}
    </div>
        <a href="{% url 'show:allitems' 'originals' %}" class="text-decoration-none">see more</a>
</div>

{% endblock %}

templates/entershow.html
{% extends 'navbar.html' %}

{% block items %}
<div class="container">
    <style>
        .style{
            width:14rem;
            height:9rem;
            border: solid;
            border-radius: 5px;
            border-color: white;
            opacity: 0.5;
        }
        .style:hover{
            opacity: 0.8;
        }
    </style>
    <div class="row">
        {% for item in items %}
        <div class="col ">
            <a href="{{item.get_absolute_url}}">
                <img src="{{item.show_caption.url}}" alt="hello" class="style">
            </a>
        </div>
        {% empty %}
        <p class="text-center fs-1">No show for this catagory</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block logo %}
<i class="bi bi-disc fs-1  text-primary"></i>
{% endblock %}
{% block form %}
    <div class="container mt-3 ">
        <form action="{% url 'auth:login' %}" method="POST">
            {% csrf_token %}
            <div class="row justify-content-center">
                
                <div class="col-12 col-md-4 " >
                    {% if signin.non_field_errors %}
                    {% for error in signin.non_field_errors %}
                        <div class="alert alert-danger alert-sm">{{error }}</div>
                    {% endfor%}
                    {% endif %}  
                </div>
                <div class="w-100"></div>
                <div class="col-12 col-md-4 ">
                    <h4>Sign In</h4>
                </div>
                <div class="w-100"></div>
                <div class="col-12 col-md-4">
                    <label class="form-label" for="{{signin.username.id_for_label}}">{{signin.username.label}}</label>
                    {{signin.username}}
                </div>
                <div class="w-100"></div>
                <div class="col-12 col-md-4">

                    <label class="form-label" for="{{signin.password.id_for_label}}">{{signin.password.label}}</label>
                    {{signin.password}}
                </div>
                <div class="w-100"></div>
                <div class="col-12 col-md-4 ">
                    <button type="submit" class="btn btn-primary w-100 mt-2">Sign In</button>
                </div>
                <div class="w-100"></div>
                <div class="col-12 col-md-4 pt-2">
                    <a href="" class="text-decoration-none">Forget Password?</a>
                    <div class="w-100"></div>
                    <hr>
                    <a href="{% url 'auth:signup' %}" class="btn btn-success w-100">Create New Account</a>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

templates/navbar.html
{% extends 'base.html' %}
{% block title %}Dasboard{% endblock%}
{% load active_link_tags %}
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'auth:home' %}"><i class="bi bi-disc  fs-3 text-primary"></i></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse " id="navbarNavDropdown">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'auth:home' %}" id="link1"><i class="bi bi-house" ></i> Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'show:allitems' 'originals' %}" id="link2"><i class="bi bi-star"></i> Originals</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'show:allitems' 'tv' %}" id="link3"><i class="bi bi-display"></i> Tv shows</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'show:allitems' 'movies' %}" id="link4"><i class="bi bi-collection"></i> Movies</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><i class="bi bi-search" id="link5"></i> Search</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
             Catagories
            </a>
            <ul class="dropdown-menu dropdown-menu-dark">
              <li><a class="dropdown-item" href="#">Catagories</a></li>
              <li><hr class="dropdown-divider"></li>
              {% for catagory in catagories %}
              <li><a class="dropdown-item" href="{{catagory.get_absolute_url}}">{{catagory}}</a></li>
              {% endfor %}
              <li><hr class="dropdown-divider"></li>
          </ul>
          </li>
        </ul>
        <div class="w-auto">
          {% if request.user.is_authenticated %}
            <div class="btn-group  dropdown ">
                <button type="button" class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                  {{request.user.first_name}} {{request.user.last_name}}
                </button>
                <ul class="dropdown-menu dropdown-menu-dark">
                    <li><a class="dropdown-item" href="#"><i class="bi bi-file-earmark-person"></i> Account</a></li>
                    <li><a class="dropdown-item" href="{% url 'show:history' %}"><i class="bi bi-archive"></i> Histrory</a></li>
                    {% if perms.shows.add_show%}
                    <li><a class="dropdown-item" href="{% url 'show:create' %}"><i class="bi bi-plus"></i> Add show</a></li>
                    <li><a class="dropdown-item" href="{% url 'show:allshow' %}"><i class="bi bi-play"></i> Shows</a></li>
                    {% endif %}
                    <li><hr class="dropdown-divider"></li>
                    <a class="btn btn-danger btn-sm mx-4 " href ="{% url 'auth:logout' %}"><i class="bi bi-arrow-return-right"></i> Sign Out</a>
                  </ul>
          {% else %}
                  <a href="{% url 'auth:login' %}" class="btn btn-link text-decoration-none btn-sm">Sign In</a>
                  <a href="{% url 'auth:signup' %}" class="btn btn-sm btn-success">Sign Up</a>
          {% endif %}
              </div>
        </div>
      </div>
    </div>
    {% if 'originals' in request.path %}
    <script>
      var doc = document.getElementById('link2');
      doc.classList.add('active')
    </script>
    {% elif 'tv' in request.path %}
    <script>
      var doc = document.getElementById('link3');
      doc.classList.add('active')
    </script>
    {% elif 'movies' in request.path %}
    <script>
      var doc = document.getElementById('link4');
      doc.classList.add('active')
    </script>
    {% elif 'search' in request.path %}
    <script>
      var doc = document.getElementById('link5');
      doc.classList.add('active')
    </script>
    {% else %}
    <script>
      var doc = document.getElementById('link1');
      doc.classList.add('active')
    </script>
    {% endif %}
  </nav>


{% endblock %}

{% block items %}
  
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% block logo %}
<i class="bi bi-disc fs-1  text-primary"></i>
{% endblock %}
{% block form %}
    <div class="container mt-3 ">
        {{signup.non_field_errors}}
        <form action="{% url 'auth:signup' %}" method="POST">
            {% csrf_token %}
            <div class="row justify-content-center">
                <div class="col col-md-4">
                    <h4>Sing Up</h4>
                </div>
                <div class="w-100"></div>
                <div class="col col-md-2">
                    <label class="form-label" for="{{singup.first_name.id_for_label}}">{{singup.first_name.label}}</label>
                    {{singup.first_name}}

                    {% if singup.first_name.errors %}
                    <script>
                        var user = '{{singup.first_name.id_for_label}}';
                        var user_add_class = document.getElementById(user);
                        user_add_class.classList.add('is-invalid')
                    </script>
                    {% for error in singup.first_name.errors %}
                        <div class="invalid-feedback">
                            {{error}}
                        </div>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="col col-md-2">
                    <label class="form-label" for="{{singup.last_name.id_for_label}}">{{singup.last_name.label}}</label>
                    {{singup.last_name}}
                    {% if singup.last_name.errors %}
                    <script>
                        var user = '{{singup.last_name.id_for_label}}';
                        var user_add_class = document.getElementById(user);
                        user_add_class.classList.add('is-invalid')
                    </script>
                    {% for error in singup.last_name.errors %}
                        <div class="invalid-feedback">
                            {{error}}
                        </div>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="w-100"></div>
                <div class="col-12 col-md-4">
                    <label class="form-label" for="{{singup.username.id_for_label}}">{{singup.username.label}}</label>
                    {{singup.username}}
                    {% if singup.username.errors %}
                    <script>
                        var user = '{{singup.username.id_for_label}}';
                        var user_add_class = document.getElementById(user);
                        user_add_class.classList.add('is-invalid')
                    </script>
                    {% for error in singup.username.errors %}
                        <div class="invalid-feedback">
                            {{error}}
                        </div>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="w-100"></div>
                <div class="col-12 col-md-4">

                    <label class="form-label" for="{{singup.password1.id_for_label}}">{{singup.password1.label}}</label>
                    {{singup.password1}}
                </div>
                <div class="w-100"></div>
                <div class="col-12 col-md-4">

                    <label class="form-label" for="{{singup.password2.id_for_label}}">{{singup.password2.label}}</label>
                    {{singup.password2}}
                    {% if singup.password2.errors %}
                        <script>
                            var element1 = '{{singup.password2.id_for_label}}';
                            var element2 = '{{singup.password1.id_for_label}}';
                            var add_class1 = document.getElementById(element1);
                            var add_class2 = document.getElementById(element2);
                            add_class1.classList.add('is-invalid')
                            add_class2.classList.add('is-invalid')
                        </script>
                        {% for error in singup.password2.errors %}
                            <div class="invalid-feedback">
                                {{error}}
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="w-100"></div>
                <div class="col-12 col-md-4 ">
                    <button type="submit" class="btn btn-primary w-100 mt-2">Create Account     </button>
                </div>
                <div class="w-100"></div>
                <div class="col-12 col-md-4 pt-2">
                    <hr>
                    <a href="{% url 'auth:login' %}" class="btn btn-secondary w-100">Already Have A Account</a>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'auth:signup' %}" method="POST">
        {% csrf_token %}
        {{htmlform}}
        {% for error in singup.errors %}
            {{error}}
        {% endfor %}
        <input type="submit" value="create">
    </form>
</body>
</html>